// LISTEN FOR NEWLY TYPES MESSAGES, 
// SEND THEM TO THE SERVER


// LISTEN FOR NEW MESSAGES FROM SERVER
// APPEND THEM TO THE MESSAGE BOX
// AUTO SCROLL TO BOTTOM

// APPEND MESSAGES TO BOX

// OPTIONAL: LISTEN FOR NEW NAME
// SEND IT TO SERVER
